/*
 * control.c
 *
 *  Created on: Nov 5, 2023
 *      Author: Haris
 */

#ifndef CORE_MIDDLEWARES_SERVICES_CONTROL_CONTROL_C_
#define CORE_MIDDLEWARES_SERVICES_CONTROL_CONTROL_C_



#endif /* CORE_MIDDLEWARES_SERVICES_CONTROL_CONTROL_C_ */
